FROM apache/airflow:latest

USER root
RUN apt-get update && \
    apt-get install -y --no-install-recommends gcc python3-dev default-libmysqlclient-dev pkg-config && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

USER airflow


RUN python -m pip install --no-cache-dir \
        pymysql \
        pandas \
        apache-airflow-providers-fab \
        apache-airflow-providers-mysql \
        apache-airflow-providers-amazon \
        -i https://mirrors.aliyun.com/pypi/simple/

RUN python -m pip install --no-cache-dir minio faker dbt-core dbt-mysql
RUN python -m pip install --no-cache-dir 'protobuf>=3.20,<5.0.0'